<?php
/**
 * @file
 * Main module file for the D8 caching system backport.
 */

require_once __DIR__ . '/includes/core.inc';
require_once __DIR__ . '/includes/block.inc';
require_once __DIR__ . '/includes/entity.inc';
require_once __DIR__ . '/includes/menu.inc';
require_once __DIR__ . '/includes/theme.inc';

// -----------------------------------------------------------------------
// Core Hooks

/**
 * Implements hook_process_html().
 */
function d8cache_process_html(&$variables) {
  // @todo Find a way to work with ajax.
  drupal_emit_cache_tags();
}

/**
 * Implements hook_emit_cache_tags().
 */
function d8cache_emit_cache_tags($tags) {
  if (variable_get('d8cache_emit_cache_tags', TRUE)) {
    drupal_add_http_header('Surrogate-Key', implode(' ', $tags));
  }
}

/**
 * Implements hook_invalidate_cache_tags().
 */
function d8cache_invalidate_cache_tags($tags) {
  // Temporary Pantheon integration.
  if (function_exists( 'pantheon_clear_edge_keys')) {
    pantheon_clear_edge_keys($tags);
  }
}

// -----------------------------------------------------------------------
// Contrib Hooks


// -----------------------------------------------------------------------
// Public API


// -----------------------------------------------------------------------
// Helper functions
